### ISSUE TITLE
Measures problem

### ISSUE THREAD

**Issue by bm-software** [deanhet/react-native-text-ticker#10]
Hi,
this is my implementation:

    <View style={{marginBottom: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: 52}}>		
		<View style={{flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
			height: 25, backgroundColor: category.color}}>
			<View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start'}}>
				...
			</View>
		
			<View style={{width: 50}}></View>
		
			<View style={{flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-start'}}>
				<Text style={[{color: colors.white.primary, padding: 3}]}>
					Created
				</Text>
				<TextTicker
					style={{fontSize: 16, fontWeight: 'bold', color: colors.white.primary, padding: 3}}
					loop
					bounce
					repeatSpacer={50}
					marqueeDelay={2000}>
					Super long piece of text is long. The quick brown fox jump
				</TextTicker>
			</View>
		</View>
    </View>

Unfortunately this doesn't work and the text doesn't slide.
I notice that the minimum distance to make the text animate is 60 character.

With

> Super long piece of text is long. The quick brown fox jump

sp with 59 characters it doesn't work.

With

>  Super long piece of text is long. The quick brown fox jump**s**

so with 60 characters it works.

This is how that piece of view looks like:
![screenshot_20180718-105434](https://user-images.githubusercontent.com/19502861/42870873-42bfa74a-8a79-11e8-9a3a-fd36d42f154b.png)

How can I solve this? Am I missing something?

**Comment by deanhet** [comment]
Hi there, 

Thanks for your example! It was super helpful in understanding what you meant.

This looks to be more of a layout/styling issue than a measuring one. I got the example to run well when I added a set width to the `Text` element that wraps around the "Created". 

If that doesn't work for you then you may want to try setting a fixed width on the the style of the `TextTicker`. I think it might be getting confused with your flex layout and this would help it define a boundary. Could even set the width dynamically by grabbing the screen width with the `Dimensions` module.

**Comment by bm-software** [comment]
@deanhet I've tried your solution but it doesn't work. To make it works I had to add `flex: 1` property on the `View` parent element of the `TextTicker`.

However, if you put a text like: `3d 0h 0m 1s ago` the same issue occurs and I have to set a text with a minimum length of 22 characters to make it works as expected. (eg. `3d 0h 0m 1s ago agoooo`).

I can't set a fixed width to `TextTicker` element because the layout is indeed dynamic and using `Dimensions` will require a lot of math work. Could you consider to support flex layout? :)

Moreover, as you've already imagined, I need to set that text dynamically from a server object but If I add a dynamic text with `{someObject.formattedCreatedOnDate}` seems that your library doesn't recognize that text, not condidering it to compute duration (125ms * string_length). 
In this case I have to had a fixed duration to make it works (but this is a workaround and not a fix).
