### ISSUE TITLE
Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference

### ISSUE THREAD

**Issue by JarrodS846** [deanhet/react-native-text-ticker#11]
Hey, I get this error randomly when using this component, the error happens like 4/5 times but if I keep reloading it eventually it will work, not too sure what the problem is. The text is there and seeing as it seems to work sometimes i'm not sure what the issue is.

This is on an Android TV as well.

## React Native Info
Environment:
  OS: Windows 10
  Node: 9.10.0
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257

Packages: (wanted => installed)
  react: 16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

**Comment by deanhet** [comment]
I've had a search around and it seems like a lot of people are having your issue. https://github.com/facebook/react-native/issues/19413

Unfortunately, it seems like Android is not maintained as well as iOS when it comes to React-Native. I'm starting to come up against this myself, the native-bridge just isn't as sturdy.

I plan on doing some work in the future to 'fix' this but right now I can't do much to combat it. 
Sorry it's not the answer you wanted to hear.

**Comment by danielalvesrs** [comment]
The problem is that we do not have the exact location of the error.
I had a line like this:
StatusBar.setBackgroundColor ('DA552F');
I forgot the #! That was enough.
Lots of attention to detail like this. It takes a lot to find.
