### ISSUE TITLE
Animation jitter when only slightly larger than container

### ISSUE THREAD

**Issue by derochedesign** [deanhet/react-native-text-ticker#123]
I'm getting this animation jitter when the text is only a little longer than the given area:

https://user-images.githubusercontent.com/38788426/218218290-29a37d7f-39f1-4aed-8d1a-d00ac153e307.mov

I tried adding a `bounceDelay` but that only makes it do the same thing but slower. 

Edit: setting `bounce={false}` does fix it, but if I wanted to let it bounce, how could i prevent it from going this fast?

**Comment by deanhet** [comment]
Hi! Have you tried the duration or bounceSpeed props?

**Comment by derochedesign** [comment]
Ah i see, i guess I just expected the bounceDelay to only delay the beginning and not also the end so I was confused. Slowing `bounceSpeed` (and adding a negative `shouldAnimateThreshold`) got me to the desired outcome. Thanks!
