### ISSUE TITLE
Can't call setState (or forceUpdate) on an unmounted component

### ISSUE THREAD

**Issue by censo** [deanhet/react-native-text-ticker#13]
Hey, from time to time I'm getting a warning attached on various devices when using this component. What's is weird but crucial, warning causes a crash on Google Pixel 
<img width="345" alt="zrzut ekranu 2018-09-11 o 09 21 29" src="https://user-images.githubusercontent.com/4599213/45344815-eb323400-b5a4-11e8-81a6-9415213fc48b.png">

Would be great if it could get fixed.

**Comment by deanhet** [comment]
Just trying to debug this. Can you give me a small example of how you're using it in your code? Are you also on the latest version of the package? That clears up a lot of unmounting issues.

**Comment by censo** [comment]
Sure. Here is the code:
```        
<TextTicker duration={3000} bounce={false} loop={false} scroll repeatSpacer={50} marqueeDelay={1000} style={gStyles.textSectionTitle}>
Super long piece of text is long. The quick brown fox jumps over the lazy dog.
</TextTicker>
```
And I'm using:
>     "react": "16.3.1",
>     ....
>     "react-native": "0.55.4",
>     "react-native-text-ticker": "0.13.0"

**Comment by deanhet** [comment]
I have an idea on the fix but can't move ahead until I can reliably replicate it. 

I've tried this on android and ios and can't recreate this issue with the just code you've provided. Can you give me a bit more of the code and what you're trying to do with it?

**Comment by joepake** [comment]
http://prntscr.com/oaxw30
Need check component unmounted before setState in calculateMetrics function.

**Comment by deanhet** [comment]
Happy to take a PR for this if it fixes any issues you're having

**Comment by joepake** [comment]
please review this PR
https://github.com/deanhet/react-native-text-ticker/pull/39
