### ISSUE TITLE
warning:You are setting the style `{ direction: ... }` as a prop

### ISSUE THREAD

**Issue by qinfensky** [deanhet/react-native-text-ticker#16]
warning:You are setting the style `{ direction: ... }` as a prop. You should nest it in a style object. E.g. `{ style: { direction: ... } }`
At present my code will cause the yellow window warning, please look at what is the reason.

my code:
                     <TextTicker
                        ref = 'TextTicker'
                        style={{ 
                            fontSize: 12,
                            color: 'white',
                        }}
                        direction={length * 500}
                        loop
                        bounce
                        repeatSpacer={50}
                        marqueeDelay={1000}
                    >
                        {this.props.notice}
                    </TextTicker>

npm version: 
    "react-native-text-ticker": "^0.13.0"

**Comment by deanhet** [comment]
`Direction` is not a valid prop for this component. Are you sure you don't mean `duration`?
