### ISSUE TITLE
A bit of offtopic, could this be used for vertical scroll?

### ISSUE THREAD

**Issue by agustif** [deanhet/react-native-text-ticker#2]
First. thanks for putting up your code, and making awesome open source projects, I would like to know if you think this repo could be extended to also animate text vertically in a view for react-native, I want to build a kinda teleprompter app, and this would certainly help.

Or maybe you know some example code that does this?

**Comment by deanhet** [comment]
There's a couple of ways I'm imagining this, could you provide an example of what you mean?

**Comment by agustif** [comment]
I want to do something like this: https://www.instagram.com/p/BhZbW-xjKkq/?tagged=script2screen

But so you can record yourself doing monologues or dramatic scenes

**Comment by deanhet** [comment]
This looks like its outside the scope of what I was trying to do with this project so I'm going to close the issue. 

However, this is how I would approach trying to build that:
- Insert your text into a `ScrollView`
- Each line of text will have to be a set height.
- Use the [scrollTo](https://facebook.github.io/react-native/docs/scrollview.html#scrollto) method on the ScrollView to scroll to your specific line.

Alternatively, you could just use a `View` and animate the `translateY` transform.
