### ISSUE TITLE
Max ticker size

### ISSUE THREAD

**Issue by daaashley** [deanhet/react-native-text-ticker#28]
Is there any reason why the ticker might not display for child arrays larger than 15 items? Oddly enough my ticker will display with up to 15 item arrays and no more, any idea why this might be? (marquee here is the array)

```javascript
const DrawingMarquee = ({ marquee }) => (
  <TextTicker
    style={styles.marquee}
    duration={40000}
    loop={true}
    bounce={true}
    repeatSpacer={0}
    marqueeDelay={0}
    easing={Easing.linear}
  >
    {marquee}
  </TextTicker>
);
```

**Comment by deanhet** [comment]
There’s nothing in the code that would set a limit like this. Which leads me to believe that the issue lies lower level within React Native itself. 

Can you provide an example of the kind of content you’re showing within the ticker?

**Comment by daaashley** [comment]
Basically I'm returning a function to the props that the ticker uses.
```javascript
<LobbySection
              onViewTicket={this.viewTicket}
               marquee={this.loadArray(this.state.scrollingEvents)}
                      />

```

The array function ends up returning the array containing:
["some text", "more text" , " . . . "]

Strangely, when the function returns an array with less than 15 strings in it, it works. Any more and it doesn't display. Maybe it exceeds some max dimension or animation property?

**Comment by daaashley** [comment]
And just for more context:
```javascript
loadArray(array) {
    console.log("Loading new Array");
    let newArray = [];
    for (var i = 0; i < array.length - 10; i++) {
      if (array[i].user != null) {
        newArray.push(
          "       " +
            array[i].user.displayName +
            " added " +
            array[i].tickets +
            " tickets to " +
            array[i].name
        );
      } else {
        newArray.push(
          "       " +
            "A user" +
            " added " +
            array[i].tickets +
            " tickets to " +
            array[i].name
        );
      }
      console.log(newArray[i]);
    }

    return newArray;
  }
```

**Comment by daaashley** [comment]
For anyone that came across this error, it turns out most devices have a pixel overflow limit somewhere around 5000px. If you are trying to scroll a string or array that is very large across the screen, it will not render if it is larger than the device limit. As a workaround, you can use multiple marquees/scrollviews that alternate substrings/subarrays of what you want to display. You can also alternate arrays within a single marquee. To do this, though, you will have to reimplement this library in a custom way.

**Comment by deanhet** [comment]
Thanks for taking the time to look into this further! Will close the issue for now but if you happen to find a good fix please don't hesitate to submit a pull request.
