### ISSUE TITLE
Updating text length would not trigger animation

### ISSUE THREAD

**Issue by EddieEJ** [deanhet/react-native-text-ticker#42]
Whenever I use `animationType={'auto'}` and the component has been passed a really short text through props, after updating to a longer string, the animation `scroll` would not trigger. The component will always keep the last effect it had initially regardless of the changes in text length. 

How can I trigger the component so that it recalculates the text length every time the text changes and decides on what animation to perform? 

My code Looks like this:

```
<View style={{flex: 1, alignItems: 'center'}}>
   <TextTicker numberOfLines={1} repeatSpacer={25}>
      {this.props.title} . 
   </TextTicker>
</View>
```

P.S. I am running version 0.18.

**Comment by deanhet** [comment]
Thanks for submitting an issue, I'm trying to understand your problem so I created a small component:

```
import React, {useState} from 'react';
import { TouchableOpacity, StyleSheet, Text, View } from 'react-native';
import TextTicker from 'react-native-text-ticker'

export default function App() {

  const [ shortText, setShortText ] = useState(true)
  return (
    <View style={styles.container}>
      <TextTicker repeatSpacer={25} animationType="auto">
      {shortText ? 'No scroll text' : 'The quick brown fox jumps over the lazy dog and then he keeps on jumping and this is a long piece of text'}
      </TextTicker>
      <TouchableOpacity onPress={() => setShortText(!shortText)}>
        <Text>Toggle</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

All this does is toggle the text inside to be really small (and static on the screen), to wide enough that it will start scrolling it. From what I understand, you're saying that when it jumps to text that should scroll, it doesn't?

The above code works for me, `No scroll text` doesn't scroll and `The quick brown fox jumps over the lazy dog and then he keeps on jumping and this is a long piece of text` does after a small pause when I press toggle. Can you please try the above code and see if it works for you? 

If you're still having issues with the above then I'll need more specific values that you're using to reproduce the issue.

**Comment by EddieEJ** [comment]
@deanhet I can confirm the issue was on my end. Everything works fine on a new project.
