### ISSUE TITLE
[Bug Report] For initial state values which are contentFits and isScrolling

### ISSUE THREAD

**Issue by pwsses** [deanhet/react-native-text-ticker#5]
Hi 
I have one suggestion.
When I using this module in the text which is fits in the container.
It always show repeat text at the first time on render function.
Because "state.contentFits" / state.isScrolling are initial value is "false"
So, when First time call render function, repeat text is shown and it display on screen. (once for render)
I change your code like...
state = { //line 49
    animating:    false,
    contentFits:  true,
    shouldBounce: false,
    isScrolling:  true
  }
It is work fine and issue fixed.
I will hope to accept my suggestion and update your module.
And it will be fixed bug in my application..
Thanks.

**Comment by deanhet** [comment]
Hi there!

I'd be more than happy to merge this if you'd like to submit your changes as a pull request

**Comment by pwsses** [comment]
Hi
I pull request my code. plz check it

**Comment by deanhet** [comment]
I've pulled your code from #6 but I don't quite understand what you mean, everything seems to be working as expected with the default version. Can you post your code/text for your `<TextTicker />`, the device you're testing on, and a screenshot?

**Comment by pwsses** [comment]
Thanks your comment
This is my code <TextTicker /> on Android (galaxy S8+)
//JS
<View style={contentTextInfoArea}>
<TextTicker
  style={contentTitle}
  duration={4000}
  loop={true}
  bounce={false}
  repeatSpacer={10}
  marqueeDelay={1500}
>
{this.title}
</TextTicker>
</View>

//Style
contentTextInfoArea: {
  height: Scale.getModerate(90),
  width: Scale.getHorizontal(180)
},
contentTitle: {
  height: Scale.getVertical(56),
  fontSize: 11,
  textAlign: 'left',
  color : '#000000',
  textAlignVertical: 'center'
},

And I can't make screenshot because it is occur instantaneously.
 ex) If my title is "test",  it is small than TextTicker(or View) width.
      it once display  "test  test" on TextTicker
      I think, it is because of
{!contentFits && !isScrolling // line 225 in index.js
            ? <View style={{ paddingLeft: repeatSpacer }}>
              <Animated.Text
                numberOfLines={1}
                {... props}
                style={[style, { transform: [{ translateX: this.animatedValue }], width: null }]}
              >
                {this.props.children}           
              </Animated.Text>
</View> : null }

At first render, contentFits, isScrolling values are false. 
So always render repeat text. it displayed on white space.

Of course, it is just once occur. After calculateMetrics, it displayed "test" 

thank you.

**Comment by deanhet** [comment]
I think I understand now. I normally develop on iOS and can't see the problem there but I'll take a look at android over the weekend. Your pull request gives me a great idea of where to start but I can't merge it as it breaks the scrolling behaviour (stops repeating text).

**Comment by danny-mon** [comment]
@deanhet 

I think this screenshot can best display @pwsses 's point. 
![Screenshot_2019-05-28-14-24-39](https://user-images.githubusercontent.com/52220857/60134883-cd833380-97a0-11e9-8ed2-897091fde295.png)

This https://github.com/deanhet/react-native-text-ticker/pull/6 seems to solve the problem
