### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by Jason-Cooke** [deanhet/react-native-text-ticker#57]
Would you happen to have a list of changes written up that could be turned into a CHANELOG, or at the very least to add as notes with each release on the releases page?

Also, thanks for developing such a useful module!

**Comment by deanhet** [comment]
There hasn't been any changelog up to this point as the feature set remained pretty static for a while. 
Changes up to this point can basically be traced through closed pull requests.

It is a good idea though so going forward (whenever the next release is), I'll add a changelog of has changed. 👍🏻

**Comment by Jason-Cooke** [comment]
@deanhet Cheers!
