### ISSUE TITLE
left to right 

### ISSUE THREAD

**Issue by rezaabaskhanian** [deanhet/react-native-text-ticker#60]
How to moving from left to right
for Language Arabic

**Comment by deanhet** [comment]
Do you mean text scrolling from right to left? Does the solution  in #18 work for you?

**Comment by MohamadKh75** [comment]
Hey
Thanks for your efforts!

Unfortunately no, it doesn't work!

I tried https://github.com/deanhet/react-native-text-ticker/issues/18 but it's focused on `bounce` mode and i can't get it to work on `scroll` mode too!

Any idea?
