### ISSUE TITLE
How to unmoutcomponent

### ISSUE THREAD

**Issue by PhamMinhKha** [deanhet/react-native-text-ticker#61]
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in TextMarquee (at CarouselCom.js:80)

**Comment by curtismenmuir** [comment]
Added a PR with fix for this: https://github.com/deanhet/react-native-text-ticker/pull/65
