### ISSUE TITLE
Missing bounceDelay or something similar

### ISSUE THREAD

**Issue by RWOverdijk** [deanhet/react-native-text-ticker#62]
Right now the code ignores the marqueeDelay after the first bounce animation.

I'd like this to be configurable instead of it being hardcoded to 0.

It's a simple thing to do (so maybe tag as good first PR). If I run into this again in the future I'll pick it up.

**Comment by deanhet** [comment]
Thanks for this, I'm just about to go on holiday but will tag this and take a look if nobody has for when I get back.
