### ISSUE TITLE
How to use for arrays of item? (Question)

### ISSUE THREAD

**Issue by drb1** [deanhet/react-native-text-ticker#71]
I have to display array's of text item and it is displaying correctly , the problem is that how can i give margin between two different items so that user can see some gap between two different items

**Comment by deanhet** [comment]
Can you give me an example of the code you're using to do this?

**Comment by drb1** [comment]
function TextSlider(props) {

    const textTickerProps = {
        scrollSpeed: 5000,
        easing: Easing.linear,
        marqueeDelay: 500,
        loop: true,
        marqueeOnMount: true,
        style:{padding:10}
    };

    return (
        <View style={{justifyContent: 'center', alignItems: 'center',}}>
            <TextTicker
                {...textTickerProps}
            >
                {props.notice.map((item, index) => {
                    return (
                        <Text key={index} onPress={() => console.log(index)}>
                            {item.notification}
                        </Text>
                    );
                })}
            </TextTicker>
        </View>
    );

}

**Comment by deanhet** [comment]
You could add style={{ paddingRight: 15 }} to your inner <Text> component?

**Comment by drb1** [comment]
no changes btw i managed by doing.  {item.notification}{'       '}
