### ISSUE TITLE
Is it possible to loop continuously without pausing?

### ISSUE THREAD

**Issue by jhclaura** [deanhet/react-native-text-ticker#78]
I want to achieve the effect of infinite text ticker scrolling, so I set the properties as below. 

```animationType={'scroll'}
easing={Easing.linear}
isRTL={false}
loop
marqueeDelay={0}
repeatSpacer={50}
```

But there's still a slight pause when the ticker loops. Would it be possible to make it scroll continuously without pausing? 
Any advice appreciated, thank you!

**Comment by Redseb** [comment]
I don't think this library supports infinite looping without pausing but I would love to see this implemented in the future. I find that setting the repeatSpacer to 0 makes the looping seem smoother.
