### ISSUE TITLE
Request for onMarqueeComplete

### ISSUE THREAD

**Issue by bluenex** [deanhet/react-native-text-ticker#8]
There is `onMarqueeComplete` props in the original project. Would you consider add it?

**Comment by deanhet** [comment]
I've just added this as a prop for new version `0.11.0`. Let me know if you have any problems with it.

**Comment by bluenex** [comment]
onMarqueeComplete: PropTypes.bool,

This line should be `PropTypes.func` right?

**Comment by deanhet** [comment]
Whoops, good catch. Pushing out an update now.
